# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class TujiaItem(scrapy.Item):
    city_en_name = scrapy.Field()
    city_cn_name = scrapy.Field()
    query_start_time = scrapy.Field()
    query_end_time = scrapy.Field()
    house_serial_number = scrapy.Field()
    house_title = scrapy.Field()
    merchant_manage = scrapy.Field()
    best_choice = scrapy.Field()
    real_shot = scrapy.Field()
    score = scrapy.Field()
    score_times = scrapy.Field()
    location = scrapy.Field()
    price = scrapy.Field()
    estate_type = scrapy.Field()
    house_square = scrapy.Field()
    bed_count = scrapy.Field()
    prefered_guests_count = scrapy.Field()
    can_cooking = scrapy.Field()
    have_wifi = scrapy.Field()
    allow_pets = scrapy.Field()
    allow_smoke = scrapy.Field()
    allow_party = scrapy.Field()
    checkin_time = scrapy.Field()
    checkout_time = scrapy.Field()
    receive_foreign_guest = scrapy.Field()
    facility_list = scrapy.Field()
    service_list = scrapy.Field()
    house_desc = scrapy.Field()
    link = scrapy.Field()
    created_at = scrapy.Field()
    updated_at = scrapy.Field()


class AirbnbItem(scrapy.Item):
    city_en_name = scrapy.Field()
    city_cn_name = scrapy.Field()
    query_start_time = scrapy.Field()
    query_end_time = scrapy.Field()
    primary_host_id = scrapy.Field()
    host_name = scrapy.Field()
    member_since = scrapy.Field()
    house_title = scrapy.Field()
    listing_id = scrapy.Field()
    price = scrapy.Field()
    deposit_fee = scrapy.Field()
    clean_fee = scrapy.Field()
    airbnb_guest_fee = scrapy.Field()
    extra_guest_fee = scrapy.Field()
    weekend_price = scrapy.Field()
    monthly_discount = scrapy.Field()
    weekly_discount = scrapy.Field()
    reserve_situation = scrapy.Field()
    house_type = scrapy.Field()
    reviews_count = scrapy.Field()
    score = scrapy.Field()
    wishlist_saved_count = scrapy.Field()
    bedrooms = scrapy.Field()
    bathrooms = scrapy.Field()
    beds = scrapy.Field()
    person_capacity = scrapy.Field()
    checkin_time = scrapy.Field()
    checkout_time = scrapy.Field()
    self_checkin = scrapy.Field()
    is_superhost = scrapy.Field()
    instant_bookable = scrapy.Field()
    allows_pets = scrapy.Field()
    allows_children = scrapy.Field()
    allows_infants = scrapy.Field()
    allows_smoking = scrapy.Field()
    allows_events = scrapy.Field()
    minimum_nights = scrapy.Field()
    cancellation_policy = scrapy.Field()
    facility_list = scrapy.Field()
    house_desc = scrapy.Field()
    location = scrapy.Field()
    created_at = scrapy.Field()
    updated_at = scrapy.Field()
